ERROR    services.entertainment_service:entertainment_service.py:36 Развлечение с ID 1 не найдено.